### ISSUE TITLE
mc_compute_stationary returns a vector with a negative element?

### ISSUE THREAD

**Issue by oyamad** [haru110jp/KMR#1]
Unittest のひな形を作ったので使ってください．

``` python
import sys
from random import uniform
import numpy as np
import unittest
from mc_tools import mc_compute_stationary


def find_stationary_with_negative_elements():
    P = np.zeros((4, 4))

    while 1:
        d = uniform(0, 1e-7)
        e = uniform(0, 1e-7)
        f = uniform(0, 1e-7)
        P[0, 0], P[0, 2] = d, 1 - d
        P[1, 0], P[1, 2] = e, 1 - e
        P[2, 0], P[2, 1] = f, 1 - f
        P[3, 3], P[3, 2] = e, 1 - e

        v = mc_compute_stationary(P)

        if np.prod(v >= 0) != 1:
            return P, v


P, v = find_stationary_with_negative_elements()
print 'P =\n', P, '\n'
print 'v =\n', v, '\n'


# Tolerance level
TOL = 1e-17

print 'TOL =', TOL, '\n'


class TestComputeStationary(unittest.TestCase):
    def setUp(self):
        self.P, self.v = P, v

    def test_markov_matrix(self):
        for i in range(len(P)):
            self.assertEqual(sum(P[i, :]), 1)

    def test_sum_one(self):
        self.assertTrue(np.allclose(sum(self.v), 1, atol=TOL))

    def test_nonnegative(self):
        self.assertEqual(np.prod(self.v >= 0-TOL), 1)

    def test_left_eigen_vec(self):
        self.assertTrue(np.allclose(np.dot(self.v, self.P), self.v, atol=TOL))

    def tearDown(self):
        pass


if __name__ == '__main__':
    suite = unittest.TestLoader().loadTestsFromTestCase(TestComputeStationary)
    unittest.TextTestRunner(verbosity=2, stream=sys.stderr).run(suite)
```

(大野くんのところでも負の要素を含む定常分布が出てきたようです．)

**Comment by oyamad** [comment]
KMR モデルの文脈で，次のような確率行列を探してみてください．
- `TOL` (許容誤差) は `test_nonnegative` が FAIL になるぎりぎりのオーダーに設定する．
  そのような値がなるべく大きくなるように． (1e-17 はきわめて小さい．)
- プレイヤーの数はなるべく小さく．

**Comment by beeleb** [comment]
利得がそのままでプレイヤーが3人のとき、εを極端に小さく(0.00000000000001)すると定常分布にそこそこ大きい負値が混ざりました([ -1.44092219e-02  -1.06782978e-16   1.49704936e-14   1.01440922e+00])。
http://docs.python.jp/2/tutorial/floatingpoint.html　
によればPythonで計算できるのは高々2^53(だいたい9*10^16)とのことなので、εが小さかったり人数が多かったりする場合ではA×(定常分布)=(1,...,1)をnp.linalg.solveで解く上で値の丸めが大量に発生していることが原因のような気がします。

**Comment by oyamad** [comment]
epsilon が 0.001 くらいで同じくらいのオーダーの誤差を生むためには，プレイヤーは何人必要か調べられますか．

2^{-53} はだいたい 10^{-16} くらいで，最初の例の誤差のオーダー 1e-17 はそれくらいですね．

**Comment by beeleb** [comment]
epsilon=0.001では13人から定常分布に負値が出始め、16人のときに10^(-2)のオーダーの負値が出ました。

**Comment by oyamad** [comment]
| epsilon | N for 1e-2 | N for 1e-1 |
| --- | --- | --- |
| 1e-1 |  |  |
| 1e-2 |  |  |
| 1e-3 | 16 |  |
| ... | ... | ... |
| 1e-14 | 3 |  |

みたいな表を作れますか．
(間は適当に．全部埋める必要はないですよ．)

**Comment by beeleb** [comment]
<table class="reference" style="width:100%">
    <tr>
        <th>epsilon</th>
        <th>N for 1e-2</th>     
        <th>N for 1e-1</th>
    </tr>
<tr>
        <td>1e-1</td>
        <td>78*</td>        
        <td>78</td>
    </tr>
    <tr>
        <td>1e-2</td>
        <td>27*</td>        
        <td>27</td>
    </tr>
    <tr>
        <td>1e-3</td>
        <td>16</td>     
        <td>18</td>
    </tr>
    <tr>
        <td>1e-4</td>
        <td>11*</td>        
        <td>11</td>
    </tr>
    <tr>
        <td>1e-6</td>
        <td>14*</td>        
        <td>14</td>
    </tr>
    <tr>
        <td>1e-8</td>
        <td>5*</td>     
        <td>5*</td>
    </tr>
    <tr>
        <td>1e-10</td>
        <td>5*</td>     
        <td>5*</td>
    </tr>
    <tr>
        <td>1e-12</td>
        <td>5*</td>     
        <td>5*</td>
    </tr>
    <tr>
        <td>1e-14</td>
        <td>3</td>      
        <td>6*</td>
    </tr>
</table>

<br>
(*記号はそれより大きいオーダーの誤差がいきなり出た場合に記しました）

マイナスが出始める人数より少し少ない人数でも、N人付近より0人付近の確率が高い、などおかしそうなものが混ざっています。

**Comment by oyamad** [comment]
Thanks!
これは逐次改訂の結果ですか？

私の環境では，N=78, 27 あたりではマイナスの要素が出てきましたが，それ以降では (全部はやってないけど) やった範囲では異常な結果は出てきませんでした．

同時改訂ではどうですか．

**Comment by beeleb** [comment]
逐次改訂によるものです。
確率行列や定常分布は<A Href="https://github.com/beeleb/Kandori-Mailath-Rob/blob/master/KMR_class.py">これ</A>を用いて求めています。
同時改訂の場合を作っていなかったので、作り次第やってみます。

**Comment by oyamad** [comment]
ちなみに，自分のコードでやったらこんな感じでした．
(p = 1/3，逐次改訂)

``` python
# N = 27, epsilon = 1e-2
# Stationary distribution
array([ -2.48255180e-02,  -3.36828636e-03,  -2.20038808e-04,
        -9.21435543e-06,  -2.77819761e-07,  -6.42196414e-09,
        -1.18327463e-10,  -1.78366133e-12,  -2.22487348e-14,
        -8.34484590e-17,  -9.59425880e-17,  -1.07363310e-16,
        -1.20471395e-16,  -1.35327791e-16,  -1.52499877e-16,
        -1.72571646e-16,  -1.95756734e-16,  -1.47184432e-16,
         8.34181730e-15,   8.10541310e-13,   6.45429448e-11,
         4.28137221e-09,   2.32361769e-07,   1.00521722e-05,
         3.33397045e-04,   7.96152144e-03,   1.21872520e-01,
         8.98245614e-01])
```

``` python
# N = 5, epsilon = 1e-8
# Markov matrix
array([[  9.99999995e-01,   5.00000000e-09,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  1.99999999e-01,   7.99999997e-01,   4.00000000e-09,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   3.99999998e-01,   5.00000008e-09,
          5.99999997e-01,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   3.00000000e-09,
          5.99999999e-01,   3.99999998e-01,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.00000000e-09,   7.99999997e-01,   1.99999999e-01],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   5.00000000e-09,   9.99999995e-01]])

# Stationary distribution
array([  9.99999975e-01,   2.49999993e-08,   9.25185865e-17,
         9.25185863e-17,   0.00000000e+00,   0.00000000e+00])
```

Python 環境，OS によって丸め方が違うのかな？
N = 5, epsilon = 1e-8 のケースも，マイナスは出てないけど，状態 0 に集中しているのは変です．
(N = 3, epsilon = 1e-14 ではマイナスが出ました．)

**Comment by beeleb** [comment]
行列はまったく同じものになっているのですが、定常分布が異なります。
こちらの環境ではN = 5, epsilon = 1e-8の条件下での定常分布は
[ -3.76246657e+00  -9.40616640e-08  -3.15616682e-16   1.44061663e-15
   1.19061664e-07   4.76246654e+00]
となっています。コードの違いによるものなのかOSの違いによるものなのかはわかりませんが。
また、同時改訂でもやってみましたが、人数の違いはあるにせよやはりどこかでマイナスが出ます。

**Comment by oyamad** [comment]
それはだいぶ離れた値ですね．

同時改訂の方も，epsilon と N の表作れますか．

**Comment by oyamad** [comment]
テストのコード書きました．
https://github.com/oyamad/test_mc_compute_stationary

みなさんの環境でも実行してみて．
(レポジトリを Fork して，SourceTree でそれのクローンをローカルにつくって，手を加えるならそれに．)

**Comment by oyamad** [comment]
課題の説明文での議論をアップデートしました：
https://github.com/OyamaZemi2014/exercises/tree/master/ex05#定常分布---その後-201488

新しい `mc_compute_stationary` でおかしな振る舞いが出ないか，見てみてください．

**Comment by haru110jp** [comment]
KMRの文脈で、簡単に次のような動作確認を行った所、N=26という比較的早い段階でエラーが出ました（延々と処理が終わらなかったのでkeyboard interruptした）
http://nbviewer.ipython.org/github/haru110jp/KMR/blob/master/Untitled2.ipynb

つぎに、mc_compute_stationary(P,precision=18)を実行したところ
array([  1.79517826e-21,   2.34545903e-22,   1.47327828e-23,
         5.92272677e-25,   1.71134065e-26,   3.78386877e-28,
         6.65504557e-30,   9.55498158e-32,   1.14034457e-33,
         2.27869558e-33,   7.70880891e-31,   2.23134976e-28,
         5.55048253e-26,   1.18951110e-23,   2.19804659e-21,
         3.49929017e-19,   4.78746636e-17,   5.60415180e-15,
         5.57613104e-13,   4.67221085e-11,   3.25419486e-09,
         1.85024222e-07,   8.36814094e-06,   2.89610443e-04,
         7.20405977e-03,   1.14688632e-01,   8.77809142e-01])
という値が得られました。（全部正）

mc_toolsのコード145行目を見ると、両方noneのときに許容範囲以上の負の値が混ざると、stationary_dists = mc_compute_stationary(P, precision=18, tol=tol)を返すようですが、以上から"tol=tol"の部分に問題があると思われます。実際、上の例のエラーも145行目から始まっています。

また、補足ですがPはN=26のまま、"precision"を30にして
mc_compute_stationary(P,precision=30)

を実行したところ
array([], dtype=float64)
が戻ってきました。

**Comment by oyamad** [comment]
すばらしい．

問題の所在を明らかにするために，私の作った `mc_compute_stationary_mpmath` で同じことやってみてください．
https://github.com/oyamad/test_mc_compute_stationary#mc_compute_stationary_mpmathpy

**Comment by haru110jp** [comment]
試行錯誤の跡です。
http://nbviewer.ipython.org/github/haru110jp/KMR/blob/master/Untitled3.ipynb

N=26の場合に関しては、mc_toolsでprecisionを修正したあとの定常分布にかなり近いです（まったく同じではなく、目分量ですが1/1000~1/10000ほどズレています）
一方、N=6の時に空の行列を返されました。上に載っていませんがN=5,N=4でも同じものを返されています。
Nを大きくすればしっかり動作する上、先生の実行例ではその程度の大きさの行列にも使えているので、この現象の原因はよくわからないです。

**Comment by oyamad** [comment]
``` python
mc_compute_stationary_mpmath(P, precision=11, irreducible=True)
```

のように `irreducible=True` として，`precision` をいろいろいじってみてください．

また別の試行として，`irreducible=True` は消して，`ltol` と `utol` を適当に設定してみてください．
